version: '3'
services:
  web:
    build: .
    restart: always
    command:  
      - "bash -c \"python manage.py runserver 0.0.0.0:8000\"
      - " && node app.js"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - content:/docker_moonlight/content

volumes:
  content:
