version: '3'
services:
  python:
    build: .
    restart: always
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - content:/docker_moonlight/content
    depends_on:
      - node

  node:
    build: 
        context: node
        dockerfile: ./Dockerfile
    restart: always
    command: bash -c "node app.js"
    ports:
      - "8001:8001"
    volumes:
      - content:content

volumes:
  content:
